.TH LIBVDEPLUG_VXVDEX 1 "May 04, 2017" "Virtual Distributed Ethernet"
.SH NAME
libvdeplug_pcap - vdeplug module for vde_switch based networks
.SH SYNOPSIS
libvdeplug_pcap.so
.SH DESCRIPTION
This libvdeplug module interconnects a client to an interface using the packet capture library
(pcap): all the data that is received by this plug is injected into interface and everything captured from that interface 
is sent to the client.

Please notice that the pcap library captures and injects packets on the net, packets sent by the host are not captured,
injected packets are not received by the host.
So several clients using libvdeplug_pcap on the same interface of the same host do not communicate (nor they communicate
with the host).

This module of libvdeplug4 can be used in any program supporting vde like
\fBvde_plug\fR, \fBkvm\fR, \fBqemu\fR, \fBuser-mode-linux\fR and \fBvirtualbox\fR.

The vde_plug_url syntax of this module is the following:
.RS
.br
\fBpcap://\fR\fIinterface_name\fR
.RE

.SH EXAMPLE
.B vde_plug vde:// pcap://eth0
.br
connects the standard vde_switch to the interface eth0.

.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").
.SH SEE ALSO
\fBvde_plug\fP(1),
